apiVersion: v1
kind: Service
metadata:
  name: pilcrow-mysql
  namespace: pilcrow
spec:
  selector:
    tier: backend
    layer: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
