apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilcrow-fpm
  namespace: pilcrow
  labels:
    tier: backend
    layer: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/wreality/pilcrow/fpm:8750aa36
          command:
            - php
          args:
            - artisan
            - migrate
            - --force --seed
          envFrom:
            - configMapRef:
                name: pilcrow
            - secretRef:
                name: pilcrow
            - secretRef:
                name: pilcrow-mysql
      containers:
        - name: fpm
          image: ghcr.io/wreality/pilcrow/fpm:8750aa36
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: pilcrow
            - secretRef:
                name: pilcrow
            - secretRef:
                name: pilcrow-mysql
