apiVersion: v1
kind: Service
metadata:
  name: pilcrow-fpm
  namespace: pilcrow
spec:
  selector:
    tier: backend
    layer: fpm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
