apiVersion: batch/v1
kind: Job
metadata:
  name: initial-migration
  namespace: pilcrow
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: ghcr.io/wreality/pilcrow/fpm-dev:8750aa36
        command:
            - php
          args:
            - artisan
            - migrate
            - --force
            - --seed
          envFrom:
            - configMapRef:
                name: pilcrow
            - secretRef:
                name: pilcrow
            - secretRef:
                name: pilcrow-mysql
      restartPolicy: Never
  backoffLimit: 2