apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: pilcrow
spec:
  selector:
    tier: backend
    layer: webserver
  ports:
    - protocol: TCP
      name: smtp
      port: 1025
      targetPort: 1025
    - protocol: TCP
      name: web
      port: 8025
      targetPort: 8025
