apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pilcrow-web
spec:
  tls:
    - hosts:
        - pilcrow.lndo.site
      secretName: pilcrow-tls
  ingressClassName: nginx
  rules:
    - host: pilcrow.lndo.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pilcrow-web
                port:
                  number: 8888
