apiVersion: v1
kind: Service
metadata:
  name: pilcrow-web
  namespace: pilcrow
spec:
  selector:
    tier: backend
    layer: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
